services:
 web:
  build: ./app
  ports:
    - "5000:5000"
  networks:
    - app-net
  depends_on:
    - db

 db:
  image: "redis:alpine"
  networks:
  - app-net
  volumes:
  - redis_data:/data
networks:
  app-net:
volumes:
  redis_data:


